[alias]
esp32 = "run --release --features=esp32   --target=xtensa-esp32-none-elf"
esp32c3 = "run --release --features=esp32c3 --target=riscv32imc-unknown-none-elf"
esp32c6 = "run --release --features=esp32c6 --target=riscv32imac-unknown-none-elf"
esp32h2 = "run --release --features=esp32h2 --target=riscv32imac-unknown-none-elf"
esp32s3 = "run --release --features=esp32s3 --target=xtensa-esp32s3-none-elf"
esp32-build = "build --release --features=esp32   --target=xtensa-esp32-none-elf"
esp32c3-build = "build --release --features=esp32c3 --target=riscv32imc-unknown-none-elf"
esp32c6-build = "build --release --features=esp32c6 --target=riscv32imac-unknown-none-elf"
esp32h2-build = "build --release --features=esp32h2 --target=riscv32imac-unknown-none-elf"
esp32s3-build = "build --release --features=esp32s3 --target=xtensa-esp32s3-none-elf"

[target.'cfg(target_arch = "riscv32")']
# runner = "espflash flash --monitor --log-format defmt"
runner = "espflash flash --monitor"
rustflags = [
  "-C",
  "link-arg=-Tlinkall.x",
  # Uncomment the following two lines if you want to use defmt
  # "-C", 
  # "link-arg=-Tdefmt.x",
]

[target.'cfg(target_arch = "xtensa")']
# Uncomment the following line if you want to use defmt
# runner = "espflash flash --monitor --log-format defmt"
runner = "espflash flash --monitor"
rustflags = [
  # GNU LD
  "-C",
  "link-arg=-Wl,-Tlinkall.x",
  "-C",
  "link-arg=-nostartfiles",
  # Uncomment the following two lines if you want to use defmt
  # "-C",
  # "link-arg=-Tdefmt.x",

  # LLD
  # "-C", "link-arg=-Tlinkall.x",
  # "-C", "linker=rust-lld",
]

[target.riscv32imc-unknown-none-elf]
# Uncomment the following line if you want to use defmt
# runner = "espflash flash --monitor --log-format defmt"
# Comment the following line if you want to use defmt
runner = "espflash flash --monitor"

[target.riscv32imac-unknown-none-elf]
# Uncomment the following line if you want to use defmt
# runner = "espflash flash --monitor --log-format defmt"
# Comment the following line if you want to use defmt
runner = "espflash flash --monitor"

[target.xtensa-esp32s3-none-elf]
# Uncomment the following line if you want to use defmt
# runner = "espflash flash --monitor --log-format defmt"
# Comment the following line if you want to use defmt
runner = "espflash flash --monitor"

[target.xtensa-esp32-none-elf]
# Uncomment the following line if you want to use defmt
# runner = "espflash flash --monitor --log-format defmt"
# Comment the following line if you want to use defmt
runner = "espflash flash --monitor"


[env]
ESP_LOG = "INFO"
# Uncomment the following line if you want to use defmt
# DEFMT_LOG = "INFO"

[unstable]
build-std = ["alloc", "core"]
