name: Build and Deploy ESP Docs

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: deploy-docs
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup temporary toolchain
        uses: dtolnay/rust-toolchain@stable
      
      - name: Install espup
        run: cargo install espup
      
      - name: Setup esp-rs toolchain
        run: espup install --toolchain esp --targets riscv32imc-unknown-none-elf --export-file ~/.cargo/env
      
      - name: Source toolchain
        run: source ~/.cargo/env && cargo +esp --version

      - name: Clean previous docs
        run: cargo +esp clean --doc

      - name: Build ESP docs
        run: cargo +esp doc --features "esp32c3 println" --target riscv32imc-unknown-none-elf --no-deps

      - name: Create redirect
        run: |
          echo '<meta http-equiv="refresh" content="0;url=esp_csi_rs/index.html">' > target/riscv32imc-unknown-none-elf/doc/index.html

      - name: Remove lock file
        run: rm -f target/riscv32imc-unknown-none-elf/doc/.lock

      - name: Upload docs artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: target/riscv32imc-unknown-none-elf/doc

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
